import { useEffect, useRef, useState } from "react";
import type { DatabaseCredentials } from "../shared/types";
import { Tooltip } from "./Tooltip";
import { api, errorMessage, isAborted, post } from "./api";
import {
  Disclosure,
  ErrorBanner,
  Icon,
  Loading,
  MaskedValue,
} from "./components";

export function DatabasePanel({
  role,
  environment,
  copy,
}: {
  role: string;
  environment: string;
  copy: (value: string) => void;
}) {
  const [credentials, setCredentials] = useState<DatabaseCredentials | null>(
    null,
  );
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [config, setConfig] = useState<{
    exists: boolean;
    path?: string;
  } | null>(null);
  const [configError, setConfigError] = useState("");
  const [syncing, setSyncing] = useState(false);
  const [notice, setNotice] = useState("");
  const syncReason =
    configError ||
    (!config
      ? "Checking PostgreSQL MCP config…"
      : !config.exists
        ? "PostgreSQL MCP config is unavailable."
        : "");
  const controller = useRef(new AbortController());
  useEffect(() => {
    const active = new AbortController();
    controller.current = active;
    return () => active.abort();
  }, []);
  useEffect(() => {
    if (!credentials) return;
    const active = new AbortController();
    setConfig(null);
    setConfigError("");
    api<{ exists: boolean; path?: string }>("/api/database/check-mcp-config", {
      signal: active.signal,
    })
      .then((data) => {
        if (!active.signal.aborted) setConfig(data);
      })
      .catch((error) => {
        if (!isAborted(error)) setConfigError(errorMessage(error));
      });
    return () => active.abort();
  }, [credentials]);
  async function sync() {
    if (!credentials || !config?.exists || syncing) return;
    setSyncing(true);
    setError("");
    setNotice("");
    try {
      const result = await post<{ message?: string }>(
        "/api/database/sync-to-mcp",
        {
          role_name: role,
          username: credentials.username,
          password: credentials.password,
        },
        controller.current.signal,
      );
      if (!controller.current.signal.aborted)
        setNotice(result.message || "Credentials synced to PostgreSQL MCP.");
    } catch (error) {
      if (!isAborted(error)) setError(errorMessage(error));
    } finally {
      if (!controller.current.signal.aborted) setSyncing(false);
    }
  }
  async function generate() {
    setLoading(true);
    setError("");
    setNotice("");
    setCredentials(null);
    try {
      const result = await post<DatabaseCredentials>(
        `/api/database/creds/${encodeURIComponent(role)}`,
        {},
        controller.current.signal,
      );
      if (!controller.current.signal.aborted) setCredentials(result);
    } catch (error) {
      if (!isAborted(error)) setError(errorMessage(error));
    } finally {
      if (!controller.current.signal.aborted) setLoading(false);
    }
  }
  return (
    <section className="detail-panel">
      <div className="page-heading">
        <div>
          <div className="eyebrow">DATABASE ROLE</div>
          <h1>
            <Icon name="database" />
            Database Credentials
          </h1>
          <p className="secret-path">{role}</p>
        </div>
      </div>
      {error && <ErrorBanner message={error} />}
      {notice && (
        <div className="success-banner" role="status">
          {notice}
        </div>
      )}
      {loading ? (
        <Loading text="Generating credentials…" />
      ) : credentials ? (
        <>
          <div className="success-banner">
            <Icon name="check" />
            <span>
              Credentials generated successfully. Vault manages their database
              lease.
            </span>
          </div>
          <div className="card">
            <div className="card-heading">
              <h2>Connection Credentials</h2>
              <span className="badge">{environment.toUpperCase()}</span>
            </div>
            <div className="credential-row">
              <div>
                <label>Username</label>
                <small>Generated by Vault</small>
              </div>
              <MaskedValue
                value={credentials.username}
                label="username"
                copy={copy}
              />
            </div>
            <div className="credential-row">
              <div>
                <label>Password</label>
                <small>Hidden by default</small>
              </div>
              <MaskedValue
                value={credentials.password}
                label="password"
                copy={copy}
              />
            </div>
            <div className="card-footer">
              <span>
                Lease duration: {credentials.lease_duration.toLocaleString()}{" "}
                seconds
              </span>
              <span>
                {credentials.renewable
                  ? "Renewable lease"
                  : "Non-renewable lease"}
              </span>
            </div>
          </div>
          <div className="credential-actions">
            <button
              className="button primary"
              onClick={() =>
                copy(
                  JSON.stringify(
                    {
                      username: credentials.username,
                      password: credentials.password,
                    },
                    null,
                    2,
                  ),
                )
              }
            >
              <Icon name="copy" />
              Copy All Credentials
            </button>
            <Tooltip
              content={syncReason || `Sync credentials to ${config?.path}`}
            >
              <span>
                <button
                  className="button"
                  aria-describedby={
                    syncReason ? "sync-availability" : undefined
                  }
                  disabled={!config?.exists || syncing}
                  onClick={() => void sync()}
                >
                  {syncing ? "Syncing…" : "Sync to PostgreSQL MCP"}
                </button>
              </span>
            </Tooltip>
            <button
              className="button"
              disabled={syncing}
              onClick={() => void generate()}
            >
              <Icon name="refresh" />
              Regenerate
            </button>
          </div>
          {syncReason && (
            <p
              id="sync-availability"
              className="muted"
              role={configError ? "alert" : undefined}
            >
              {syncReason}
            </p>
          )}
          <Disclosure className="lease-details" title="Lease details">
            <dl>
              <dt>Lease ID</dt>
              <dd>
                <code>{credentials.lease_id}</code>
              </dd>
              <dt>Role</dt>
              <dd>{credentials.role}</dd>
            </dl>
          </Disclosure>
        </>
      ) : (
        <div className="empty-state generate-state">
          <div className="empty-illustration">
            <Icon name="database" />
          </div>
          <h2>Generate Database Credentials</h2>
          <p>
            Create a new username and password for <strong>{role}</strong>.
          </p>
          <button className="button primary" onClick={() => void generate()}>
            <Icon name="key" />
            Generate Credentials
          </button>
        </div>
      )}
    </section>
  );
}
